### ISSUE TITLE
worktipsd: undefined symbol: _ZN5boost15program_options3argE

### ISSUE THREAD

**Issue by smartree** [Vordas/worktips#1]
Ubuntu 16.04.3 LTS
x86_64 GNU/Linux
with boost 1.58 and ln -s 1.55.0 so file:

ll /usr/lib/x86_64-linux-gnu/libboost*
-rw-r--r-- 1 root root    2514 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_atomic.a
lrwxrwxrwx 1 root root      25 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_atomic.so -> libboost_atomic.so.1.58.0
-rw-r--r-- 1 root root    5848 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_atomic.so.1.58.0
-rw-r--r-- 1 root root  125450 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_chrono.a
lrwxrwxrwx 1 root root      25 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_chrono.so -> libboost_chrono.so.1.58.0
-rw-r--r-- 1 root root   31112 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.58.0
-rw-r--r-- 1 root root  167000 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_date_time.a
lrwxrwxrwx 1 root root      28 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_date_time.so -> libboost_date_time.so.1.58.0
-rw-r--r-- 1 root root   68088 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.58.0
-rw-r--r-- 1 root root  234296 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_filesystem.a
lrwxrwxrwx 1 root root      29 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_filesystem.so -> libboost_filesystem.so.1.58.0
lrwxrwxrwx 1 root root      55 Mar 13 04:48 /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.55.0 -> /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
-rw-r--r-- 1 root root   97064 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
-rw-r--r-- 1 root root 1553814 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_program_options.a
lrwxrwxrwx 1 root root      34 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_program_options.so -> libboost_program_options.so.1.58.0
lrwxrwxrwx 1 root root      60 Mar 13 06:27 /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.55.0 -> /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.58.0
-rw-r--r-- 1 root root  514968 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.58.0
-rw-r--r-- 1 root root 1276342 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_serialization.a
lrwxrwxrwx 1 root root      32 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_serialization.so -> libboost_serialization.so.1.58.0
-rw-r--r-- 1 root root  395992 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.58.0
-rw-r--r-- 1 root root   47862 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_system.a
lrwxrwxrwx 1 root root      25 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_system.so -> libboost_system.so.1.58.0
lrwxrwxrwx 1 root root      51 Mar 13 04:47 /usr/lib/x86_64-linux-gnu/libboost_system.so.1.55.0 -> /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0
-rw-r--r-- 1 root root   14496 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0
-rw-r--r-- 1 root root  352882 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_thread.a
lrwxrwxrwx 1 root root      25 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_thread.so -> libboost_thread.so.1.58.0
-rw-r--r-- 1 root root  154480 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
-rw-r--r-- 1 root root  889758 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_wserialization.a
lrwxrwxrwx 1 root root      33 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_wserialization.so -> libboost_wserialization.so.1.58.0
-rw-r--r-- 1 root root  297856 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_wserialization.so.1.58.0

**Comment by Vordas** [comment]
Compiling on Ubuntu 14 trusty:

sudo apt-get update
sudo apt-get install build-essential git cmake libboost1.55-all-dev
pull the latest repo - then make

Boost version must be 1.55-all-dev and must not be in conflict with the newer or older versions of boost.

More on installing/un-installing boost: https://stackoverflow.com/questions/8430332/uninstall-boost-and-install-another-version

Please let me know if that helped.

**Comment by smartree** [comment]
not work for Ubuntu16, cannot downgrade the package from apt-get.

but above error msg is appearing after i removed 1.58 and complied 1.55 from boost source.
with boost1.55 compiled or ln -s:
./worktipsd --help
./worktipsd: symbol lookup error: ./worktipsd: undefined symbol: _ZN5boost15program_options3argE

with boost1.58:
./worktipsd --help
./worktipsd: error while loading shared libraries: libboost_program_options.so.1.55.0: cannot open shared object file: No such file or directory

But why not to link /usr/lib/x86_64-linux-gnu/libboost_filesystem.so without version number?
How can compile and make from github source?

**Comment by bgonuller** [comment]
same problem in here

**Comment by Vordas** [comment]
Just updated the readme.md with Ubuntu version of the tutorial. So far all tuts are guaranteed to work only on Ubuntu 14.

Ubuntu 16 tutorial is being made and will soon be added to current list of compilation instructions along with some other systems/versions.

Sorry about the confusion.

**Comment by bgonuller** [comment]
ok i will try on Ubuntu 14. thank you

**Comment by bgonuller** [comment]
hmmm,
23:36:46.063779 ERROR CHECKPOINT VALIDATION FAILED
23:36:46.523716 INFO [24.253.12.30:17239 OUT] 

wrong chain ... ??

**Comment by Vordas** [comment]
Can you tell me which checkpoint has failed? Code was updated recently there could be a typo.

**Comment by bgonuller** [comment]
8304

**Comment by bgonuller** [comment]
23:50:16.804988 ERROR CHECKPOINT VALIDATION FAILED
23:50:18.738276 INFO [187.181.142.110:54064 INC] Sync data returned unknown top block: 8303 -> 8985 [682 blocks (0 days) behind]
23:50:18.738276 INFO SYNCHRONIZATION started
23:50:21.015802 ERROR CHECKPOINT FAILED FOR HEIGHT 8304. EXPECTED HASH: <c627e394fd08bf2f48e54a9ac89f7677e7f7b9ea07d48d3c1a6187cbb46c029b>, FETCHED HASH: <23735c3527de236133d578bcff3a2a3fb6d0e19e2b9de0e9c03487583abc3791>

**Comment by Vordas** [comment]
Could you try recompiling now with latest code. The problematic checkpoints should now be removed. Please let me know your block height after the syncing of the client is done. Thanks

**Comment by bgonuller** [comment]
i will try to re-compile in 1 hours...

**Comment by bgonuller** [comment]
compiling just now - %60

**Comment by bgonuller** [comment]
00:55:22.262637 INFO [24.253.12.30:17239 OUT] SYNCHRONIZED OK
 yep this time ok.
