### ISSUE TITLE
Failed to check ring signature for tx <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>

### ISSUE THREAD

**Issue by smartree** [Vordas/worktips#2]
Ubuntu 14

04:49:05.593319 INFO **********************************************************************
04:49:05.600166 INFO Mining has started with 1 threads, good luck!
04:49:05.600191 INFO Miner thread was started [0]
04:49:31.275738 INFO 
04:49:31.275738 INFO **********************************************************************
04:49:31.275738 INFO The daemon will start synchronizing with the network. It may take up to several hours.
04:49:31.275738 INFO 
04:49:31.275738 INFO You can set the level of process detailization* through "set_log <level>" command*, where <level> is between 0 (no details) and 4 (very verbose).
04:49:31.275738 INFO 
04:49:31.275738 INFO Use "help" command to see the list of available commands.
04:49:31.275738 INFO 
04:49:31.275738 INFO Note: in case you need to interrupt the process, use "exit" command. Otherwise, the current progress won't be saved.
04:49:31.275738 INFO **********************************************************************
06:00:05.298659 INFO Failed to check ring signature for tx <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:00:05.298823 INFO tx used wrong inputs, rejected
06:00:05.298900 ERROR Transaction verification failed: <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:00:05.298984 INFO [144.202.105.62:17239 OUT] Tx verification failed
06:05:49.869417 INFO Failed to check ring signature for tx <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:05:49.869666 ERROR Transaction verification impossible: <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:05:49.932603 INFO Failed to check ring signature for tx <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:05:49.932741 INFO Block <eab2c42d73f591e89def30b6e9eb1df5303e08a9adcf26f4fb7f20a9277dfa2f> has at least one transaction with wrong inputs: <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:05:49.971821 INFO Failed to check ring signature for tx <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:05:50.002483 INFO Failed to check ring signature for tx <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:06:07.521914 INFO [144.202.105.62:17239 OUT] Sync data returned unknown top block: 2437 -> 2439 [2 blocks (0 days) behind] 
06:06:07.521914 INFO SYNCHRONIZATION started
06:06:08.513154 INFO Failed to check ring signature for tx <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:06:08.513342 INFO Block <eab2c42d73f591e89def30b6e9eb1df5303e08a9adcf26f4fb7f20a9277dfa2f> has at least one transaction with wrong inputs: <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:06:08.549281 INFO Failed to check ring signature for tx <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:06:08.577976 INFO Failed to check ring signature for tx <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:06:35.105278 INFO [144.202.105.62:17239 OUT] Sync data returned unknown top block: 2437 -> 2440 [3 blocks (0 days) behind] 
06:06:35.105278 INFO SYNCHRONIZATION started
06:06:35.915130 INFO Failed to check ring signature for tx <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:06:35.915260 INFO Block <eab2c42d73f591e89def30b6e9eb1df5303e08a9adcf26f4fb7f20a9277dfa2f> has at least one transaction with wrong inputs: <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:06:35.950215 INFO Failed to check ring signature for tx <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:06:35.977665 INFO Failed to check ring signature for tx <53b8aec167aed001801f6caa7f3ac46b375b20146668cfce4019fb80d09f7f0b>
06:07:02.686035 INFO [144.202.105.62:17239 OUT] Sync data returned unknown top block: 2437 -> 2441 [4 blocks (0 days) behind] 
06:07:02.686035 INFO SYNCHRONIZATION started

**Comment by Vordas** [comment]
Clone the latest source -> delete the blockchain folder -> rebuild -> sync from scratch

If the TX error repeats, do the above and start a daemon with a flag: --add-exclusive-node 45.63.91.13

**Comment by samvicky26** [comment]
Its solved,

If it occurs again, open the issue again
