### ISSUE TITLE
error transfer use ./simplewallet

### ISSUE THREAD

**Issue by crashpower** [Vordas/worktips#3]
[WTIP mywallet]: transfer
Note: You can type cancel at any time to cancel the transaction

What address do you want to transfer to?: WtipYszuYviY2i9T4NPcRbWeMwUVvLNqQPtN3jpeRr3N9tx8n2xJQav1onk1UBjhzgVnWPQQPnE6W75aTQRrPvBY5VS816pv1R
Invalid address! It should start with WTIP!

I've tried with another address but same error

**Comment by Vordas** [comment]
This issue has been fixed in the latest client relealse. Please download it from here: https://github.com/Vordas/worktips/releases/tag/v1.0.2.3

Thanks
